core/models/payment.py
from extensions import db

class Payment(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type = db.Column(db.Integer, nullable=False)
    code = db.Column(db.String(20), nullable=True)
    description = db.Column(db.String(200), nullable=False)
    due_date = db.Column(db.DateTime, nullable=True)
    pay_date = db.Column(db.DateTime, nullable=False)
    value = db.Column(db.DECIMAL(8,2), nullable=False)
    id_supplier = db.Column(db.Integer, foreign_key=True, nullable=True)

    def __repr__(self):
        return "<Payment(description='%s', type='%s', value='%s')>" % (
            self.description,
            self.type,
            self.value
        )

core/forms/payment.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, DateField, DecimalField, SubmitField, SelectField, validators

class PaymentForm(FlaskForm):
    type = SelectField("Tipo", [validators.DataRequired()], choices=[(1, "A Pagar"),(2, "Pago")])
    description = TextAreaField("Descrição", [validators.DataRequired(), validators.Length(min=1, max=200)])
    code = StringField("Código", [validators.DataRequired(), validators.Length(min=1, max=20)])
    due_date = DateField("Data de Vencimento", [validators.DataRequired()])
    pay_date = DateField("Data de Pagamento", [validators.DataRequired()])
    value = DecimalField("Valor(R$)", [validators.DataRequired()])
    supplier = StringField("Fornecedor", [validators.DataRequired()])
    save = SubmitField("Salvar")

login/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from core.models.user import User
from core.forms.user import UserForm
from flask_bcrypt import check_password_hash

logon = Blueprint("logon", __name__, template_folder="template")
api = '/login'

@logon.route(f'{api}/')
def login():
    next = request.args.get('next')
    form = UserForm()
    return render_template('login.html', form=form, next=next)

@logon.route(f'{api}/autenticar', methods=['POST',])
def autenticar():
    form = UserForm(request.form)
    user = User.query.filter_by(nickname=form.nickname.data).first()
    password = check_password_hash(user.password, form.password.data)

    if user and password:
        session['loguser'] = user.nickname
        flash(f'{user.nickname} logado')
        next_page = request.form['next']
        return redirect(next_page)
    else:
        flash('Usuário não logado.')
        return redirect(url_for('logon.login'))

@logon.route(f'{api}/logout')
def logout():
    session["loguser"] = None
    flash("Lgout efetuado com sucesso")
    return redirect(url_for("logon.login"))

payment/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from core.forms.payment import PaymentForm
from core.models.payment import Payment
from core.models.supplier import Supplier
import locale
from extensions import db

payment = Blueprint("payment", __name__, template_folder="templates")
api = '/payment'

@payment.route(f'{api}/')
def index():
    payment_list = Payment.query.order_by(Payment.id).all()

    for item in payment_list:
        if (item.description == 'RESRE'):
            item.description = 'Teste'

        date = item.pay_date
        date = (f'{date.strftime("%d")}/{date.strftime("%m")}/{date.strftime("%Y")}')
        item.pay_new_date = date

        locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
        locale_value = locale.currency(item.value, grouping=True, symbol=None)
        item.new_value = locale_value

        if (item.id_supplier != None):
            filter_supplier = Supplier.query.filter_by(id=item.id_supplier).first()
            supplier_name = filter_supplier.name
            item.supplier_name = supplier_name

        if item.type == 2:
            item.type_paid = True
        else:
            item.type_paid = False

    return render_template('list.html', titulo='Pagamentos', payments=payment_list)


@payment.route(f'{api}/new')
def new():

    if "loguser"not in session or session["loguser"] == None:
        return redirect(url_for("logon.login", next=url_for("payment.new")))

    form = PaymentForm()
    supplier_list = Supplier.query.order_by(Supplier.id)
    return render_template('register.html', titulo='Lançar Pagamento', form=form, suppliers=supplier_list)


@payment.route(f'{api}/create', methods=['POST', ])
def create():

    form = PaymentForm(request.form)

    if not form.validate_on_submit():
        return redirect(url_for('new'))

    code = form.code.data
    type = form.type.data
    description = form.description.data
    due_date = form.due_date.data
    pay_date = form.pay_date.data
    value = form.value.data
    supplier = form.supplier.data

    new_payment = Payment(code=code, type=type, description=description, due_date=due_date, pay_date=pay_date,
                          value=value, id_supplier=supplier)
    db.session.add(new_payment)
    db.session.commit()

    flash('Pagamento adicionado!')
    return redirect(url_for('payment.index'))


@payment.route(f'{api}/new_pay/<int:id>')
def new_pay(id):

    if "loguser"not in session or session["loguser"] == None:
        return redirect(url_for("logon.login", next=url_for("payment.new")))

    payment = Payment.query.filter_by(id=id).first()
    form = PaymentForm()

    form.description.data = payment.description
    form.description.render_kw = {'readonly': True}
    form.code.data = payment.code
    form.code.render_kw = {'readonly': True}
    form.type.data = payment.type
    form.type.render_kw = {'readonly': True}
    form.due_date.data = payment.due_date
    form.due_date.render_kw = {'readonly': True}
    form.pay_date.data = payment.pay_date
    form.pay_date.render_kw = {'readonly': True}
    form.supplier.data = payment.id_supplier
    supplier_id = payment.id_supplier
    form.supplier.data = Supplier.query.filter_by(id=supplier_id).first().name
    form.supplier.render_kw = {'readonly': True}
    form.value.data = payment.value
    form.value.render_kw = {'readonly': True}
    form.save.render_kw = {'value': 'Pagar'}

    return render_template('payment.html', titulo='Pagar', id=id, form=form)


@payment.route(f'{api}/payment', methods=['POST', ])
def pay():
    form = PaymentForm(request.form)

    payment = Payment.query.filter_by(id=request.form['id']).first()
    payment.code = form.code.data

    payment.type = 2

    db.session.add(payment)
    db.session.commit()

    flash('Duplicata paga!')

    return redirect(url_for("payment.index"))


@payment.route(f'{api}/edit/<int:id>')
def edit(id):

    if "loguser"not in session or session["loguser"] == None:
        return redirect(url_for("logon.login", next=url_for("payment.new")))

    form = PaymentForm();

    supplier_list = Supplier.query.order_by(Supplier.id)
    payment = Payment.query.filter_by(id=id).first()

    form.code.data = payment.code
    form.description.data = payment.description
    form.due_date.data = payment.due_date
    form.pay_date.data = payment.pay_date
    form.value.data = payment.value

    supplier_id = payment.id_supplier
    supplier_name = Supplier.query.filter_by(id=supplier_id).first().name

    return render_template('edit.html', form=form, titulo=payment.code, id=id, suppliers=supplier_list,
                           supplier_id=supplier_id, supplier_name=supplier_name)


@payment.route(f'{api}/update', methods=['POST', ])
def update():

    if "loguser"not in session or session["loguser"] == None:
        return redirect(url_for("logon.login", next=url_for("payment.new")))

    form = PaymentForm(request.form)

    payment = Payment.query.filter_by(id=request.form['id']).first()

    payment.code = form.code.data
    payment.description = form.description.data
    payment.pay_date = form.pay_date.data
    payment.due_date = form.due_date.data
    payment.value = form.value.data
    payment.id_supplier = form.supplier.data

    db.session.add(payment)
    db.session.commit()

    flash('Duplicata atualizada!')

    return redirect(url_for("index"))

templates/edit.html
{% extends "template.html" %}

{% block conteudo %}

<form method="post" action={{url_for('payment.update')}}>
     <fieldset>
         {{form.csrf_token()}}
         <input type="hidden" name="id" value="{{id}}" />
         <div class="form-group inputBox">
             {{ form.code.label(class="form-label")}}
             {{ form.code(class="form-control")}}
         </div>
         <div class="form-group inputBox">
             {{ form.description.label(class="form-label") }}
             {{ form.description(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.due_date.label(class="form-label") }}
             {{ form.due_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.pay_date.label(class="form-label") }}
             {{ form.pay_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.value.label(class="form-label") }}
             {{ form.value(class="form-control") }}
         </div>
         <div class="form-group inputBox ">
             {{ form.supplier.label(class="form-label") }}
             <select name="supplier" class="form-select">
                 <option value="{{supplier_id}}" style="font-weight: bold">{{supplier_name}}</option>
                 {% for s in suppliers %}
                    <option value="{{s.id}}">{{s.name}}</option>
                 {% endfor %}
             </select>
         </div>
         <div class="form-group buttons">
            {{ form.save(class="btn btn-primary") }}
            <a class="btn btn-danger" href="{{url_for('payment.index')}}">Voltar</a>
        </div>
     </fieldset>

</form>

{% endblock %}

templates/list.html
{% extends "template.html" %}

{% block conteudo %}

        <a class="btn btn-primary" href="{{ url_for('payment.new') }}">Novo</a>
        <a class="btn btn-primary" href="{{ url_for('logon.login') }}">Login</a>
        <a class="btn btn-warning" href="{{ url_for('logon.logout') }}">Logout</a>

        <div class="table-overflow">
            <table class="table table-overflow table-striped table-responsive table-bordered">
                <thead class="thead-default">
                    <tr>
                        <th>Código</th>
                        <th>Descrição</th>
                        <th>Data Pagamento</th>
                        <th>Valor</th>
                        <th>Fornecedor</th>
                        <th>Pagar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for payment in payments %}
                    <tr>
                        <td>{{ payment.code }}</td>
                        <td>{{ payment.description }}</td>
                        <td>{{ payment.pay_new_date }}</td>
                        <td>{{ payment.new_value }}</td>
                        <td>{{ payment.supplier_name}}</td>

                        <td>
                            {% if payment.type_paid %}
                            Pago
                            {% else %}
                            <a class="btn btn-primary" href="{{ url_for('payment.new_pay', id=payment.id) }}">
                                 Pagar
                             </a>
                            {% endif %}
                            <a class="btn btn-primary" href="{{ url_for('payment.edit', id=payment.id) }}">
                                 Editar
                             </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <div class="container">

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul id="messages" class="list-unstyled">
                {% for message in messages %}
                    <li class="alert alert-success">{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <h1>Faça seu Login</h1>

        <form method="POST" action="{{url_for('logon.autenticar')}}">
            <input type="hidden" name="next" value="{{next or url_for('payment.index')}}"/>

            {{form.csrf_token()}}

            <div class="form-group">
                {{form.nickname.label(class="form-label")}}
                {{form.nickname(class="form-control")}}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-label")}}
                {{form.password(class="form-control")}}
            </div>
            <div class="form-group buttons">
                {{form.login(class="btn btn-primary")}}
            </div>
        </form>
    </div>

    <link rel="stylesheet" href={{url_for('static', filename='bootstrap.css' )}}>
    <link rel="stylesheet" href={{url_for('static', filename='app.css' )}}>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

</body>
</html>

templates/payment.html
{% extends "template.html" %}

{% block conteudo %}

<form method="post" action={{url_for('payment.pay')}}>
     <fieldset>
         {{form.csrf_token()}}
         <input type="hidden" name="id" value="{{id}}" />
         <div class="form-group inputBox">
             {{ form.code.label(class="form-label")}}
             {{ form.code(class="form-control")}}
         </div>
         <div class="form-group inputBox">
             {{ form.description.label(class="form-label") }}
             {{ form.description(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.due_date.label(class="form-label") }}
             {{ form.due_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.pay_date.label(class="form-label") }}
             {{ form.pay_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.value.label(class="form-label") }}
             {{ form.value(class="form-control") }}
         </div>
         <div class="form-group inputBox ">
            {{form.supplier.label(class="form-label")}}
            {{form.supplier(class="form-control")}}
         </div>
         <div class="form-group buttons">
            {{ form.save(class="btn btn-primary") }}
            <a class="btn btn-danger" href="{{url_for('payment.index')}}">Voltar</a>
        </div>
     </fieldset>

</form>

{% endblock %}

templates/register.html
{% extends "template.html" %}

{% block conteudo %}

<form method="post" action={{url_for('payment.create')}}>
     <fieldset>
         {{form.csrf_token()}}
         <div class="form-group inputBox">
             {{ form.type.label(class="form-label") }}
             {{ form.type(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.code.label(class="form-label") }}
             {{ form.code(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.description.label(class="form-label") }}
             {{ form.description(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.due_date.label(class="form-label") }}
             {{ form.due_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.pay_date.label(class="form-label") }}
             {{ form.pay_date(class="form-control") }}
         </div>
         <div class="form-group inputBox">
             {{ form.value.label(class="form-label") }}
             {{ form.value(class="form-control") }}
         </div>
         <div class="form-group inputBox ">
             {{ form.supplier.label(class="form-label") }}
             <select name="supplier" class="form-select">
                 {% for s in suppliers %}
                    <option value="{{s.id}}">{{s.name}}</option>
                 {% endfor %}
             </select>
         </div>
         <div class="form-group buttons">
            {{ form.save(class="btn btn-primary") }}
             <a class="btn btn-danger" href="{{url_for('payment.index')}}">Voltar</a>
        </div>
     </fieldset>

</form>

{% endblock %}

templates/template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scake=1">
    <title>Pagamentos</title>
</head>
<body>
<div class="container">

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul id="messages" class="list-unstyled">
            {% for message in messages %}
                <li class="alert alert-success">{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <div class="page-header">
        <br>
        <h6>Bem vindo!</h6>
        <h3>{{titulo}}</h3>
    </div>

    {% block conteudo %}{% endblock %}

    <link rel="stylesheet" href={{url_for('static', filename='bootstrap.css' )}}>
    <link rel="stylesheet" href={{url_for('static', filename='app.css' )}}>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</div>
</body>
</html>